services:
  - type: web
    name: task-manager-backend
    env: node
    plan: free
    region: singapore # Closest to India
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
